version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '8080:8080'